apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: naro-vorn3227-spring-api-certificate
  namespace: naro-vorn3227-spring-api
spec:
  secretName: naro-vorn3227-spring-api-secret-tls
  commonName: naro-vorn3227-spring-api.assessify.org
  dnsNames:
  - naro-vorn3227-spring-api.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
